%% 1 - 500 (预留)
-define(P_XX_KEEP_END,                  500).
-define(P_C_ROLE_LOGIN,                 1010). % 角色登录
-define(P_S_ROLE_LOGIN_OK,              1020). % 登录成功
-define(P_C_SCENE_REQ_PLAYERS,          2010). % 请求玩家列表
-define(P_S_SCENE_PLAYERS,              2020). % 场景玩家列表
-define(P_S_SCENE_ENTER,                2030). % 玩家进入场景
-define(P_S_SCENE_EXIT,                 2040). % 玩家退出场景
-define(P_C_SCENE_POS_ROT,              2050). % 位置和旋转
-define(P_S_SCENE_POS_ROT_OK,           2060). % 位置和旋转
-define(P_C_SCENE_ANIM_MOVE,            2070). % 动画-行走
-define(P_S_SCENE_ANIM_MOVE_OK,         2080). % 动画-行走
